[package]
name    = "atlantix-eda" # the name of the package
version = "0.1.1"    # the current version, obeying semver
authors = ["James <fpga@atlantixeng.com>"]
description = "Programmatically generated libraries for PCB Design."
repository = "https://github.com/saturn77/atlantix-eda.git"

[dependencies]
num-traits = "0.2.14"
fs_extra = "1.2.0"


[lib]
name = "generate"

